### ISSUE TITLE
Greece is not a supported country

### ISSUE THREAD

**Issue by FinvasiaGlobal** [google-gemini/generative-ai-swift#164]
Is there a particular reason for that?

**Comment by singhniraj08** [comment]
@FinvasiaGlobal, Thank you reporting this issue. The Gemini API and Google AI Studio are available in the following [countries and territories](https://ai.google.dev/gemini-api/docs/available-regions#available_regions). If you're not in one of these countries or territories, try [Gemini Pro in Vertex AI](https://cloud.google.com/vertex-ai#build-with-gemini). 
This repository is for issues related to Gemini Swift SDK. For issues related to Gemini API, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below.

![image](https://github.com/google-gemini/generative-ai-swift/assets/110809167/ffe1b2bb-e54a-4ee8-a040-b84e7a76ec26)

**Comment by morganchen12** [comment]
Closing since this isn't an SDK issue.
