### ISSUE TITLE
Add support for `code execution` tool

### ISSUE THREAD

**Issue by longseespace** [google-gemini/generative-ai-swift#183]
### Description of the feature request:

Add support for the `Code execution` feature

https://ai.google.dev/gemini-api/docs/code-execution?lang=python

### What problem are you trying to solve with this feature?

Use `code execution` tool with Gemini 1.5 Pro

**Comment by andrewheard** [comment]
Hi @longseespace, thanks for the feature request. I don't have a specific date (🇨🇦/🇺🇸 holidays this week may slow things down) but wanted to let you know it's our current prioritized feature.

**Comment by longseespace** [comment]
I implemented it here but not sure about code quality etc. Should I create a PR? 😁

https://github.com/longseespace/generative-ai-swift/commit/dad49b6e47571dd9973d218d46d63ff7d6646437

**Comment by andrewheard** [comment]
> I implemented it here but not sure about code quality etc. Should I create a PR? 😁
> 
> [longseespace@dad49b6](https://github.com/longseespace/generative-ai-swift/commit/dad49b6e47571dd9973d218d46d63ff7d6646437)

Thanks, @longseespace! If you're interested in making a PR, please see the steps in [How to Contribute](https://github.com/google-gemini/generative-ai-swift/blob/main/docs/CONTRIBUTING.md).
