### ISSUE TITLE
Data accuracy issue with gemini-1.5-flash-latest Vs gemini-1.5-pro-latest on MultiModel 

### ISSUE THREAD

**Issue by skoru01** [google-gemini/generative-ai-swift#190]
### Description of the bug:

I am using gemini-1.5-flash-latest for find products from images and im getting pretty text as some time python and sometimes as json text but data is more accurate. But as per Gen AI document, for response as json we needs to use gemini-1.5-pro-latest through configuration but im getting single object from image for Pro model. 

### Actual vs expected behavior:

**gemini-1.5-flash-latest**: expected to get JSON response always but sometimes getting Python and something pretty json text
**gemini-1.5-pro-latest**: getting JSON text but only one object coming out multiple data.

**Comment by singhniraj08** [comment]
@skoru01, Thank you reporting this issue. This looks like an intermittent error and should work now. 
This repository is for issues related to Swift SDK client bugs or improvements and the client doesn't control the service's responses. For issues related to Gemini API, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below. You can also post this issue on [Google AI forum](https://discuss.ai.google.dev/).

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)
