### ISSUE TITLE
Device Check

### ISSUE THREAD

**Issue by MikesHorcrux** [google-gemini/generative-ai-swift#193]
### Description of the feature request:

Are you looking to implement device check by chance so there is a possibility to use this in a production environment?

### What problem are you trying to solve with this feature?

Wanting to use this in a prod environment in a safe manner without the cost of a server.

**Comment by paulb777** [comment]
The similar product, [Vertex AI for Firebase](https://firebase.google.com/docs/vertex-ai), supports Device Check via Firebase App Check.

**Comment by MikesHorcrux** [comment]
Thank you Ill Close this as its no longer needed
