### ISSUE TITLE
JSON mode glitches out when asked to make a codeblock in markdown

### ISSUE THREAD

**Issue by Visual-Studio-Coder** [google-gemini/generative-ai-swift#200]
### Description of the bug:

The response stops generating randomly, and causes an incomplete JSON to be formed.

### Actual vs expected behavior:

It says something like 

"What is the following code supposed to do?\n\n"

instead of 
"What is the following code supposed to do?\n\n```java
System.out.print("helloworld");```"

It just stops generating the prompt for some reason. this is also recreatable in the AI Studio

**Comment by andrewheard** [comment]
Hi @Visual-Studio-Coder, would you mind filing feedback from AI Studio when it fails? It's in the triple dots overflow menu: 
![AI Studio - Send Feedback Screenshot](https://github.com/user-attachments/assets/9a1eb78e-fcc2-4c40-b8a4-d570889df94b)

Currently it doesn't sound like this is an SDK issue but if you have a reproducible example, feel free to include the details here and I can share them with some backend folks.

**Comment by Visual-Studio-Coder** [comment]
Ok thank you. I just decided to send it here because I just didn't know who to contact. Yk how it is with Google right? 😅

https://aistudio.google.com/app/prompts?state=%7B%22ids%22:%5B%221SvilaBYudHeewpfChp8a4_3IRLLPXFhI%22%5D,%22action%22:%22open%22,%22userId%22:%22116531269555057652166%22,%22resourceKeys%22:%7B%7D%7D&usp=sharing
